[project]
name = "ChouetteBot"
version = "0.0.1"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "aiohttp~=3.14.3",
    "discord-py[speed]~=2.7.1",
    "python-dotenv~=1.2.2",
    "skyhelper-networth~=0.0.1a8",
    "tomlkit~=0.15.1",
    "tzdata; os_name=='nt'",
]

[dependency-groups]
dev = [
    "pre-commit~=4.0",
    "ruff==0.16.0",
]

[tool.ruff]
line-length = 99

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ASYNC",
    "B",
    "C4",
    "E",
    "ERA",
    "F",
    "I",
    "ICN",
    "N",
    "RET",
    "RUF",
    "SIM",
    "T10",
    "T20",
    "TID",
    "UP",
    "W",
]
ignore = ["E501"]
flake8-tidy-imports.ban-relative-imports = "all"
