[project]
name = "ChouetteBot"
version = "0.0.1"
readme = "README.md"
license = "MIT"
requires-python = "==3.13.*"
dependencies = [
    "aiohttp~=3.14.3",
    "amulet-mutf8",
    "audioop-lts",
    "brotli",
    "cffi",
    "discord-py[speed]~=2.7.1",
    "pycares",
    "python-dotenv~=1.2.2",
    "skyhelper-networth~=0.0.1a8",
    "tomlkit~=0.15.1",
    "tzdata; os_name=='nt'",
    "zstandard",
]

[dependency-groups]
dev = [
    "prek~=0.4",
    "ruff==0.15.22",
]

[tool.ruff]
line-length = 99

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ASYNC",
    "B",
    "C4",
    "E",
    "ERA",
    "F",
    "I",
    "ICN",
    "N",
    "RET",
    "RUF",
    "SIM",
    "T10",
    "T20",
    "TID",
    "UP",
    "W",
]
ignore = ["E501"]
flake8-tidy-imports.ban-relative-imports = "all"

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'armv7l'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]

[[tool.uv.index]]
name = "piwheels"
url = "https://piwheels.org/simple"
explicit = true

[tool.uv.sources]
amulet-mutf8 = { index = "piwheels", marker = "sys_platform == 'linux' and platform_machine == 'armv7l'" }
audioop-lts = { index = "piwheels", marker = "sys_platform == 'linux' and platform_machine == 'armv7l'" }
brotli = { index = "piwheels", marker = "sys_platform == 'linux' and platform_machine == 'armv7l'" }
cffi = { index = "piwheels", marker = "sys_platform == 'linux' and platform_machine == 'armv7l'" }
pycares = { index = "piwheels", marker = "sys_platform == 'linux' and platform_machine == 'armv7l'" }
zstandard = { index = "piwheels", marker = "sys_platform == 'linux' and platform_machine == 'armv7l'" }
