[project]
name = "chouettebot"
version = "0.0.1"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "aiohttp~=3.14.3",
    "discord-py[speed]~=2.7.1",
    "python-dotenv~=1.2.2",
    "skyhelper-networth~=0.0.4",
    "tomlkit~=0.15.1",
    "tzdata; os_name=='nt'",
]

[dependency-groups]
dev = [
    "prek~=0.4",
    "ruff==0.16.5",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.ruff]
line-length = 99

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"

[tool.ruff.lint]
select = [
    "A",     # flake8-builtins
    "ANN",   # flake8-annotations
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "BLE",   # flake8-blind-except
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez
    "E",     # pycodestyle-errors
    "ERA",   # eradicate
    "F",     # pyflakes
    "FA",    # flake8-future-annotations
    "FBT",   # flake8-boolean-trap
    "FLY",   # flynt
    "FURB",  # refurb
    "I",     # isort
    "ICN",   # flake8-import-conventions
    "INP",   # flake8-no-pep420
    "ISC",   # flake8-implicit-str-concat
    "N",     # pep8-naming
    "PERF",  # perflint
    "PGH",   # pygrep-hooks
    "PIE",   # flake8-pie
    "PL",    # pylint
    "PTH",   # flake8-use-pathlib
    "RET",   # flake8-return
    "RUF",   # ruff
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "T10",   # flake8-debugger
    "T20",   # flake8-print
    "TC",    # flake8-type-checking
    "TID",   # flake8-tidy-imports
    "TRY",   # tryceratops
    "UP",    # pyupgrade
    "W",     # pycodestyle-warnings
]
ignore = [ "E501" ]
flake8-tidy-imports.ban-relative-imports = "all"

[tool.pyproject-fmt]
indent = 4
generate_python_version_classifiers = false
table_format = "long"
sub_table_spacing = "\n"
