name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: Concise description of the feature"
labels: enhancement
assignees:
    - Zalk0
    - gylfirst

body:
    -   type: markdown
        attributes:
            value: |
                Thanks for taking the time to open a feature request! Please provide us with the following information:

    -   type: input
        id: feature
        attributes:
            label: Feature description
            description: A clear and concise description of what the feature is.
            placeholder: Describe the feature you would like to see

    -   type: textarea
        id: motivation
        attributes:
            label: Motivation
            description: Please explain why this feature should be implemented and how it would be used.
            placeholder: Explain the motivation behind this feature request

    -   type: textarea
        id: alternatives
        attributes:
            label: Alternatives
            description: Describe any alternative solutions or features you've considered.
            placeholder: Describe any alternative solutions or features

    -   type: input
        id: additional-context
        attributes:
            label: Additional context
            description: Add any other context or screenshots about the feature request here.
            placeholder: Add any other context or screenshots
