name: Ruff

on: [ pull_request, push ]

jobs:
    ruff:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                args: [ "check", "format --diff" ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Ruff
                uses: chartboost/ruff-action@v1
                with:
                    args: ${{ matrix.args }}
