name: Ruff

on: [ pull_request, push ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Ruff Lint
                uses: chartboost/ruff-action@v1
    format:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Ruff Format
                uses: chartboost/ruff-action@v1
                with:
                    args: "format --diff"
