name: Ruff

on: [ pull_request, push ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: chartboost/ruff-action@v1
        with:
          args: "check"
      - name: Format
        uses: chartboost/ruff-action@v1
        with:
          args: "format"
